In [3]:
import numpy as np

In [4]:
pricesArr = [5.99,6.99,22.49,99.99,4.99,49.99]


In [5]:
prices = np.array((pricesArr))
print(prices)

[ 5.99  6.99 22.49 99.99  4.99 49.99]


In [6]:
sum  = prices.sum()
mean = prices.mean()
max = prices.max()
min = prices.min()
print("Sum : ",sum)
print("mean : ",mean)
print("max : ",max)
print("min : ",min)

Sum :  190.44
mean :  31.74
max :  99.99
min :  4.99


2D Array

In [9]:
two_dArray = prices.reshape(3,2)
print(two_dArray)

[[ 5.99  6.99]
 [22.49 99.99]
 [ 4.99 49.99]]


 5.99 + 22.49 + 4.99 = 33.47
 6.99 +99.99 + 49.99 = 156.97

In [ ]:
sumOfFirstRowOfAll = two_dArray.sum(axis=0)   
sumOfFirstRowOfAll

array([ 33.47, 156.97])

In [14]:
sumOfFirstColOfAll = two_dArray.sum(axis=1) 
sumOfFirstColOfAll

array([ 12.98, 122.48,  54.98])