In [4]:
import numpy as np

In [ ]:
sales1 = [0,5,155,0,518]
sales2 = [0,1827,616,317,325]
sales = np.array((sales1,sales2))
print(sales+2)  # this can't be done on normal python

[[   2    7  157    2  520]
 [   2 1829  618  319  327]]


In [ ]:
print("Original Array : \n",sales)  # this can't be done on normal python
print("\n")
quantity = sales[0,:] # first row
price = sales[1,:] # second row
print(quantity)

Original Array : 
 [[   0    5  155    0  518]
 [   0 1827  616  317  325]]


[0 0]
