In [1]:
import numpy as np

In [5]:
arr1 = [1,2,3]
arr2 = [1,2,3]
arr3 = [1,2,3]
test_array = np.array((arr1,arr2,arr3))
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [10]:
oneArr = test_array +1 # add one to all
print(oneArr)

[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [11]:
test_array + np.array([1,2,3]) # add this to all row

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

Final Excercise

In [16]:
import pandas as pd
retail_df = pd.read_csv("./retail_2016_2017.csv",skiprows=range(1,11000),nrows=1000) 
family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

Family 
 ['AUTOMOTIVE' 'BABY CARE' 'BEAUTY' ... 'PRODUCE'
 'SCHOOL AND OFFICE SUPPLIES' 'SEAFOOD']
Sales 
 [   0.       0.       0.    ... 2419.729  121.      16.   ]
