Filtering


In [2]:
import numpy as np

In [3]:
salesArr = [0,5,12,34,45,56,0,90]
sales = np.array((salesArr))
print(sales)

[ 0  5 12 34 45 56  0 90]


In [7]:
sales ==0  # gives true / false array

array([ True, False, False, False, False, False,  True, False])

In [13]:
sales[(sales <10) | (sales==90)]

array([ 0,  5,  0, 90])