Filtering


In [2]:
import numpy as np

In [3]:
salesArr = [0,5,12,34,45,56,0,90]
sales = np.array((salesArr))
print(sales)

[ 0  5 12 34 45 56  0 90]


In [7]:
sales ==0  # gives true / false array

array([ True, False, False, False, False, False,  True, False])

In [13]:
sales[(sales <10) | (sales==90)]

array([ 0,  5,  0, 90])

Complex things we can do

In [26]:
products = np.array((["aaple", "mango", "banana","pineapple","grapes"]))
salesofProduct = np.array([10, 0, 5, 0, 8])
unsoldProduct = products[salesofProduct==0]
print(unsoldProduct)

['mango' 'pineapple']


In [28]:
salesofProduct[salesofProduct==0  ]=11
salesofProduct

array([10, 11,  5, 11,  8])