Indexing

In [1]:
import numpy as np

In [ ]:
arr = np.array(([1,2,3,4,5,6,7,8,9,10]))
print(arr[-1]) 
print(arr[1])

10
2


Slicing

In [15]:
print(arr[:5])  # default start point is 0

[1 2 3 4 5]


In [ ]:
print(arr[1::2]) # last argument is step

[2]


slicing on 2d array [row,col]

In [ ]:
two_Darray = arr.reshape(2,5)
print("Original Array \n",two_Darray)
print("\n")
# print("Slicing Array : \n  ",two_Darray[1])
print("Slicing Array : \n  ",two_Darray[:,1:])  #[:] means all row

Original Array 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Slicing Array : 
   [[ 2  3  4  5]
 [ 7  8  9 10]]


In [47]:
ages = np.array([5, 10, 15, 19, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

youth_ages =ages[1:4]
adult_ages  = ages[4:14]
senior_ages  =ages[14:]

Excercise

In [81]:
array = np.random.random(9).reshape(3,3)
print("Original Array \n",array)
print("\n")
print("First Two Rows \n",array[0:2])
print("\n")
print("First Col \n",array[:,0])  ## all rows and 0th col 
print("\n")
print("Second Number in Third Row \n",array[2,1])


Original Array 
 [[0.05733992 0.94989294 0.96796108]
 [0.23791344 0.10878106 0.47534115]
 [0.68162953 0.3269068  0.104078  ]]


First Two Rows 
 [[0.05733992 0.94989294 0.96796108]
 [0.23791344 0.10878106 0.47534115]]


First Col 
 [0.05733992 0.23791344 0.68162953]


Second Number in Third Row 
 0.3269067981255327
