Numpy basics

In [2]:
import numpy as np

Numpy Arrays

1D Arrays

In [3]:
list = [1,2,3]
arr_1d = np.array(list)
print(arr_1d)

[1 2 3]


2D Arrays

In [4]:
array1 = [1,2,3]
array2 = [4,5,6]
arr_2d = np.array([array1,array2])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


Diff Between List & numpy Array

In [5]:
py_list  =[1,2,3] # Python List
multiply_List = py_list *2
print(multiply_List)

[1, 2, 3, 1, 2, 3]


In [6]:
numpy_array = np.array([1,2,3]) ## Numpy Array
multiply_NumpyArr = numpy_array *2
print(multiply_NumpyArr)

[2 4 6]


As We See that numpy is correctly doing multiply of arrays

In [7]:
import time
start = time.time()
pyList = [i*2 for i in range(100000)]
print(f"List Operation time {time.time() - start}" )

start =time.time()
npArray = np.arange(100000) *2
print(f"Np Array Operation time {time.time() - start}" )

List Operation time 0.007999897003173828
Np Array Operation time 0.0


Creating Array From Scratch

In [8]:
zeroesArray = np.zeros((3,4)) # zeros array
print("Zeros Array \n",zeroesArray)
print("\n")
onesArray  = np.ones((4,5)) # ones array
print("ones Array \n",onesArray)


Zeros Array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ones Array 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Array of any numbers

In [9]:
numberArray = np.full((2,3),7)  # first para is tuple and another is number[constant]
print(numberArray)

[[7 7 7]
 [7 7 7]]


Random In Numpy  [random is a class on python and multiple methods init]

In [10]:
random = np.random.random((3,4))
print(random) 

[[0.60290417 0.06488363 0.60270507 0.72183725]
 [0.74406342 0.771027   0.76964765 0.13940345]
 [0.34017668 0.08229119 0.69267239 0.80550305]]


SEQUENCE IN NUMPY

In [11]:
seq = np.arange(1,10 ,2)  # last para is for step [default=1 means it will do one by one]
# in here we have 2 means skip 1 element in every iteration
# range are exclusive outer boundary means it will go till 9 if 10 is end
print(seq)

[1 3 5 7 9]


Vector , Matrix And Tensor

In [12]:
Vector= np.array([1,2,4])
print("This is Vector on Numpy \n", Vector)

This is Vector on Numpy 
 [1 2 4]


In [13]:
list1 = [1,2,3]
list2 = [4,5,6]
Matrix = np.array([list1,list2])
print("This is Matrix on Numpy \n" ,Matrix)

This is Matrix on Numpy 
 [[1 2 3]
 [4 5 6]]


In [14]:
list1 = [1,2]
list2 = [3,4]
list3 = [5,6]
list4 = [7,8]
Tensor = np.array([[
    [list1,list2],
    [list3,list4],
]])
print("This is Tensor \n" , Tensor)

This is Tensor 
 [[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


Array Properties

In [15]:
arr1 = [1,2,3]
arr2 = [4,5,6]
array = np.array([arr1,arr2])
print("Shape : ",array.shape)
print("Dimensions : ",array.ndim)
print("Size : ",array.size)
print("Data Type : ",array.dtype)

Shape :  (2, 3)
Dimensions :  2
Size :  6
Data Type :  int32


Array Reshaping

In [16]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape((2,3))
print("Reshaped : \n",reshaped)

Reshaped : 
 [[1 2 3]
 [4 5 6]]


Flatten Array

In [17]:
flatten = reshaped.flatten() 
print("Flatten : \n",flatten)

Flatten : 
 [1 2 3 4 5 6]


In [18]:
raveled = reshaped.ravel() # modify the original array
print("reveled : \n " ,raveled)
print(arr)

reveled : 
  [1 2 3 4 5 6]
[1 2 3 4 5 6]


LinSpace

In [19]:
list1 = np.linspace(1,10) # creates float number [we can also add start ,stop , step]
print(list1)

list2 = np.arange(1,10)
print(list2)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[1 2 3 4 5 6 7 8 9]


in linspace we define start,end and multiplication value

In [20]:
linSpace = np.linspace(0,100,10) 
print(linSpace)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


np.zeroes((row,cols),dtype)

In [21]:
zeroArr = np.zeros((2,2),dtype=int)
print(zeroArr)

[[0 0]
 [0 0]]


In [22]:
lin = np.linspace(0,100,5)
print(lin)

[  0.  25.  50.  75. 100.]


In [23]:
np.zeros(100,"int").reshape(10,10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Creating Random Numbers

In [25]:
random = np.linspace(0,1,9).reshape(3,3)
print(random)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [26]:
myArray = np.arange(10,101,10).reshape(5,2)
print(myArray)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


Slicing & Indexing

In [56]:
list1 = [1,2,3,4,5,6,7,8,9,10]
arr = list1[1:6:2]
print(arr)

[2, 4, 6]
