1. Convert this list into a NumPy array.

2. Count how many non-zero doses the patient took (i.e. actual medicine taken).

3. Calculate the total dose taken in a day.

4. Calculate the average dose (excluding zero doses).

In [ ]:
import numpy as np

In [2]:
dosesArray = [250, 500, 500, 0, 250, 0, 500, 250]
doses = np.array((dosesArray))
doses

array([250, 500, 500,   0, 250,   0, 500, 250])

In [5]:
dosesTaken = doses[doses!=0]
dosesTaken

array([250, 500, 500, 250, 500, 250])

In [6]:
dosesTaken.sum()

2250

In [7]:
dosesTaken.mean()

375.0

1. Convert this list into a NumPy array.

2. Find the median severity score.

3. Determine the standard deviation of the severity scores (how varied the scores are).

4. Identify which severity scores are greater than 3.



In [9]:
symptomSeverityArr =  [2, 3, 1, 5, 3, 4, 2, 1, 5, 3]
symptomSeverity = np.array((symptomSeverityArr))
symptomSeverity

array([2, 3, 1, 5, 3, 4, 2, 1, 5, 3])

In [12]:
np.median(symptomSeverity)

3.0

In [14]:
np.std(symptomSeverity)

1.374772708486752

In [13]:
symptomSeverity[symptomSeverity >3]

array([5, 4, 5])

1. Convert this list into a NumPy array.

2. Calculate the sum of the quantities for the first 5 patients.

3. Determine the maximum and minimum medicine quantity prescribed.

4. Multiply the quantities by a factor of 2 (double the medicine dosage).

In [15]:
medicineQuantitiesArr =[5, 10, 15, 20, 25, 30, 35, 40]
medicineQuantities = np.array((medicineQuantitiesArr))
medicineQuantitiesArr

[5, 10, 15, 20, 25, 30, 35, 40]

In [19]:
firstFive = medicineQuantities[0:5].sum()
firstFive

75

In [22]:
medicineQuantities.max()
medicineQuantities.min()

5

In [23]:
total = medicineQuantities *2
total

array([10, 20, 30, 40, 50, 60, 70, 80])

1. Convert this list into a NumPy array.

2. Find the average price of the medicines.

3. Create a new array where each price is increased by 10%.

4. Determine how many medicines have a price greater than 250.

In [24]:
medicinePricesArr =[50, 100, 150, 200, 250, 300, 350, 400]
medicinePrices = np.array((medicinePricesArr))
medicinePrices

array([ 50, 100, 150, 200, 250, 300, 350, 400])

In [25]:
np.average(medicinePrices)

225.0

In [33]:
medicinePrices + (medicinePrices  /10)

array([ 55., 110., 165., 220., 275., 330., 385., 440.])

In [35]:
len(medicinePrices[medicinePrices >250])

3

1. Convert this list into a NumPy array.

2. Calculate the mean and standard deviation of patient ages.

3. Determine the age range (difference between the maximum and minimum age).

4. Find the age group (you decide the categories) for each patient:

5. Below 30 → "Young"

6. 30–50 → "Middle-aged"

7. Above 50 → "Senior"

In [36]:
patientAgesArr = [22, 35, 58, 40, 61, 45, 50, 27, 38, 33]
patientAges = np.array((patientAgesArr))

In [37]:
mean = np.mean(patientAges)
std = np.std(patientAges)

In [39]:
ageRanges = patientAges.max() - patientAges.min()
print(ageRanges)

39


In [45]:
arr = np.where(patientAges <30 ,"Young" , np.where((patientAges>=30) & (patientAges < 50), "middle","senior"))
print(arr)

['Young' 'middle' 'senior' 'middle' 'senior' 'middle' 'senior' 'Young'
 'middle' 'middle']
