In [1]:
import numpy as np

In [6]:
inventory = np.array(([12,15,6,0,13,0,4,0]))
products = ["apple" , "banana","bike" ,"jacket","mobile","bike","pc","laptop"]

np.where(inventory <=0 , "out of stock" , products)

array(['apple', 'banana', 'bike', 'out of stock', 'mobile',
       'out of stock', 'pc', 'out of stock'], dtype='<U12')

In [13]:
ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])

adult_ages = np.where(ages >=18)
print(adult_ages)

(array([0, 3, 4, 5, 6, 8, 9], dtype=int64),)


Excercise

In [14]:
productsArr = ["salad","bread","mustard","rare tomato","cola","gourmet ice cream"]
products = np.array((productsArr))
products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [25]:
pricesArr = [5.99,6.99,22.49,99.99,4.99,49.99]
prices = np.array((pricesArr))
print(prices)

[ 5.99  6.99 22.49 99.99  4.99 49.99]


In [29]:
filtered  =products[prices >=25]

In [32]:
fancy_feast_special = filtered[1]= "cola"
filtered

array(['rare tomato', 'cola'], dtype='<U17')

In [37]:
shippingCost =  np.where(prices>20 , 0,5)
shippingCost

array([5, 5, 0, 0, 5, 0])

In [38]:
mask = (prices >25) | (products=="cola")
products[mask]

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')